"use client";

import * as React from "react";
import {
  Plus,
  Copy,
  Check,
  ExternalLink,
  Trash2,
  KeyRound,
  Users,
  MapPin,
  QrCode,
} from "lucide-react";
import { Card, StatusPill, EmptyRow } from "@/components/admin/ui";
import { Button } from "@/components/ui/Button";
import { Sheet } from "@/components/ui/Sheet";
import { cn } from "@/lib/utils";
import {
  createTable,
  updateTableStatus,
  deleteTable,
} from "@/app/[locale]/admin/tables/actions";

interface TableRow {
  id: string;
  code: string;
  label: string;
  area: string;
  seats: number;
  passcode: string;
  status: string;
}

interface TablesGridProps {
  vendorId: string;
  country: string;
  slug: string;
  theme: string;
  tables: TableRow[];
  t: TablesTranslations;
}

export type TablesTranslations = {
  addTable: string;
  tableCount_one: string;
  tableCount_other: string;
  noTablesYet: string;
  qrAutoGenerated: string;
  tableCode: string;
  tableCodeHint: string;
  tableCodePlaceholder: string;
  tableCodeRequired: string;
  tableLabel: string;
  tableLabelHint: string;
  area: string;
  seats: string;
  customerUrl: string;
  copyLink: string;
  copy: string;
  copied: string;
  viewMenu: string;
  toggleStatus: string;
  delete: string;
  deleteConfirmFull: string;
  couldNotAddTable: string;
  createTable: string;
  cancel: string;
  clickToChangeStatus: string;
};

const STATUS_OPTIONS = ["available", "occupied", "bill-requested"] as const;

function buildCustomerUrl(
  country: string,
  slug: string,
  code: string,
  theme: string
) {
  const base = `/qr/${country}/${slug}?table=${encodeURIComponent(code)}`;
  return theme ? `${base}&theme=${encodeURIComponent(theme)}` : base;
}

function CopyButton({ value, copy, copied }: { value: string; copy: string; copied: string }) {
  const [didCopy, setDidCopy] = React.useState(false);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(value);
    } catch {
      /* clipboard may be unavailable */
    }
    setDidCopy(true);
    window.setTimeout(() => setDidCopy(false), 1600);
  }

  return (
    <button
      type="button"
      onClick={handleCopy}
      className={cn(
        "grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-line bg-surface text-muted transition-colors hover:bg-surface-2 hover:text-ink",
        didCopy && "border-success/40 text-success"
      )}
      aria-label={didCopy ? copied : copy}
      title={didCopy ? copied : copy}
    >
      {didCopy ? <Check size={16} /> : <Copy size={16} />}
    </button>
  );
}

function TableCard({
  table,
  origin,
  customerUrl,
  t,
}: {
  table: TableRow;
  origin: string;
  customerUrl: string;
  t: TablesTranslations;
}) {
  const [isPending, startTransition] = React.useTransition();
  const fullUrl = origin ? `${origin}${customerUrl}` : customerUrl;
  const qrSrc = `https://api.qrserver.com/v1/create-qr-code/?size=160x160&margin=4&data=${encodeURIComponent(
    fullUrl
  )}`;

  function cycleStatus() {
    const idx = STATUS_OPTIONS.indexOf(
      table.status as (typeof STATUS_OPTIONS)[number]
    );
    const next = STATUS_OPTIONS[(idx + 1) % STATUS_OPTIONS.length];
    startTransition(() => {
      void updateTableStatus(table.id, next);
    });
  }

  function remove() {
    if (
      !window.confirm(
        t.deleteConfirmFull.replace("{label}", table.label)
      )
    )
      return;
    startTransition(() => {
      void deleteTable(table.id);
    });
  }

  const busy = isPending;

  return (
    <Card className={cn("flex flex-col gap-4", busy && "opacity-70")}>
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <h3 className="truncate text-base font-bold">{table.label}</h3>
            <span className="rounded-md bg-surface-2 px-1.5 py-0.5 font-mono text-xs text-muted">
              {table.code}
            </span>
          </div>
          <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted">
            <span className="inline-flex items-center gap-1">
              <MapPin size={12} /> {table.area}
            </span>
            <span className="inline-flex items-center gap-1">
              <Users size={12} /> {table.seats}
            </span>
            <span className="inline-flex items-center gap-1">
              <KeyRound size={12} /> {table.passcode}
            </span>
          </div>
        </div>
        <button
          type="button"
          onClick={cycleStatus}
          disabled={busy}
          title={t.clickToChangeStatus}
          className="shrink-0 disabled:pointer-events-none"
        >
          <StatusPill status={table.status} />
        </button>
      </div>

      <div className="flex items-center gap-4">
        <div className="grid h-[120px] w-[120px] shrink-0 place-items-center overflow-hidden rounded-xl border border-line bg-white p-1">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={qrSrc}
            alt={`QR code for ${table.label}`}
            width={112}
            height={112}
            className="h-28 w-28"
          />
        </div>
        <div className="min-w-0 flex-1">
          <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-muted">
            {t.customerUrl}
          </p>
          <p className="mb-2 break-all font-mono text-xs leading-snug text-ink/80">
            {customerUrl}
          </p>
          <div className="flex items-center gap-2">
            <CopyButton value={fullUrl} copy={t.copyLink} copied={t.copied} />
            <a
              href={customerUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex h-9 flex-1 items-center justify-center gap-1.5 rounded-xl bg-brand-soft px-3 text-sm font-semibold text-brand transition-opacity hover:opacity-90"
            >
              <ExternalLink size={15} /> {t.viewMenu}
            </a>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-between border-t border-line pt-3">
        <button
          type="button"
          onClick={cycleStatus}
          disabled={busy}
          className="text-xs font-semibold text-muted transition-colors hover:text-ink disabled:pointer-events-none"
        >
          {t.toggleStatus}
        </button>
        <button
          type="button"
          onClick={remove}
          disabled={busy}
          className="inline-flex items-center gap-1 text-xs font-semibold text-danger transition-opacity hover:opacity-80 disabled:pointer-events-none"
        >
          <Trash2 size={14} /> {t.delete}
        </button>
      </div>
    </Card>
  );
}

export function TablesGrid({
  vendorId,
  country,
  slug,
  theme,
  tables,
  t,
}: TablesGridProps) {
  const [open, setOpen] = React.useState(false);
  const [origin, setOrigin] = React.useState("");
  const [isPending, startTransition] = React.useTransition();
  const [error, setError] = React.useState<string | null>(null);

  const [code, setCode] = React.useState("");
  const [label, setLabel] = React.useState("");
  const [area, setArea] = React.useState("");
  const [seats, setSeats] = React.useState(2);

  React.useEffect(() => {
    setOrigin(window.location.origin);
  }, []);

  function resetForm() {
    setCode("");
    setLabel("");
    setArea("");
    setSeats(2);
    setError(null);
  }

  function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!code.trim()) {
      setError(t.tableCodeRequired);
      return;
    }
    setError(null);
    startTransition(async () => {
      try {
        await createTable(vendorId, {
          code: code.trim(),
          label: label.trim(),
          seats,
          area: area.trim(),
        });
        resetForm();
        setOpen(false);
      } catch (err) {
        setError(err instanceof Error ? err.message : t.couldNotAddTable);
      }
    });
  }

  const tableCountStr = tables.length === 1
    ? t.tableCount_one.replace("{count}", String(tables.length))
    : t.tableCount_other.replace("{count}", String(tables.length));

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted">{tableCountStr}</p>
        <Button size="sm" onClick={() => setOpen(true)}>
          <Plus size={16} /> {t.addTable}
        </Button>
      </div>

      {tables.length === 0 ? (
        <EmptyRow>{t.noTablesYet}</EmptyRow>
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
          {tables.map((table) => (
            <TableCard
              key={table.id}
              table={table}
              origin={origin}
              customerUrl={buildCustomerUrl(country, slug, table.code, theme)}
              t={t}
            />
          ))}
        </div>
      )}

      <Sheet
        open={open}
        onClose={() => {
          setOpen(false);
          setError(null);
        }}
        title={t.addTable}
        height="auto"
      >
        <form onSubmit={submit} className="space-y-4 px-5 pb-8 pt-2">
          <div className="flex items-center gap-2 rounded-xl bg-brand-soft/60 p-3 text-xs text-brand">
            <QrCode size={16} className="shrink-0" />
            <span>{t.qrAutoGenerated}</span>
          </div>

          <div>
            <label
              htmlFor="table-code"
              className="mb-1 block text-sm font-semibold"
            >
              {t.tableCode}
            </label>
            <input
              id="table-code"
              value={code}
              onChange={(e) => setCode(e.target.value)}
              placeholder={t.tableCodePlaceholder}
              autoFocus
              className="h-11 w-full rounded-xl border border-line bg-surface px-3 text-[15px] outline-none focus:border-brand"
            />
            <p className="mt-1 text-xs text-muted">{t.tableCodeHint}</p>
          </div>

          <div>
            <label
              htmlFor="table-label"
              className="mb-1 block text-sm font-semibold"
            >
              {t.tableLabel}
            </label>
            <input
              id="table-label"
              value={label}
              onChange={(e) => setLabel(e.target.value)}
              placeholder={t.tableCodePlaceholder}
              className="h-11 w-full rounded-xl border border-line bg-surface px-3 text-[15px] outline-none focus:border-brand"
            />
            <p className="mt-1 text-xs text-muted">
              {t.tableLabelHint.replace("{code}", code || "…")}
            </p>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label
                htmlFor="table-area"
                className="mb-1 block text-sm font-semibold"
              >
                {t.area}
              </label>
              <input
                id="table-area"
                value={area}
                onChange={(e) => setArea(e.target.value)}
                placeholder={t.area}
                className="h-11 w-full rounded-xl border border-line bg-surface px-3 text-[15px] outline-none focus:border-brand"
              />
            </div>
            <div>
              <label
                htmlFor="table-seats"
                className="mb-1 block text-sm font-semibold"
              >
                {t.seats}
              </label>
              <input
                id="table-seats"
                type="number"
                min={1}
                max={40}
                value={seats}
                onChange={(e) => setSeats(Number(e.target.value))}
                className="h-11 w-full rounded-xl border border-line bg-surface px-3 text-[15px] outline-none focus:border-brand"
              />
            </div>
          </div>

          {error && (
            <p className="rounded-xl bg-danger/10 px-3 py-2 text-sm font-medium text-danger">
              {error}
            </p>
          )}

          <Button type="submit" fullWidth loading={isPending}>
            {t.createTable}
          </Button>
        </form>
      </Sheet>
    </div>
  );
}
