import { LayoutGrid, Armchair, CheckCircle2, Users } from "lucide-react";
import { getTranslations } from "next-intl/server";
import { requireSession } from "../actions";
import { db } from "@/lib/db";
import { PageHeader, StatCard, EmptyRow } from "@/components/admin/ui";
import { TablesGrid } from "@/components/admin/tables/TablesGrid";

export const dynamic = "force-dynamic";

export default async function TablesPage() {
  const t = await getTranslations("admin.tables");
  const session = await requireSession();

  const vendor = session.vendorId
    ? await db.vendor.findUnique({ where: { id: session.vendorId } })
    : await db.vendor.findFirst({ orderBy: { createdAt: "asc" } });

  if (!vendor) {
    return (
      <>
        <PageHeader title={t("pageTitle")} subtitle={t("pageSubtitle")} />
        <EmptyRow>{t("noVendor")}</EmptyRow>
      </>
    );
  }

  const tables = await db.diningTable.findMany({
    where: { vendorId: vendor.id },
    orderBy: { code: "asc" },
  });

  const total = tables.length;
  const occupied = tables.filter((t) => t.status === "occupied").length;
  const available = tables.filter((t) => t.status === "available").length;
  const totalSeats = tables.reduce((sum, t) => sum + t.seats, 0);

  const tableData = tables.map((t) => ({
    id: t.id,
    code: t.code,
    label: t.label ?? `Table ${t.code}`,
    area: t.area ?? "Main",
    seats: t.seats,
    passcode: t.passcode,
    tableToken: t.tableToken ?? null,
    status: t.status,
  }));

  return (
    <>
      <PageHeader title={t("pageTitle")} subtitle={t("pageSubtitle")} />

      <div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard
          label={t("total")}
          value={String(total)}
          icon={<LayoutGrid size={18} />}
        />
        <StatCard
          label={t("occupied_stat")}
          value={String(occupied)}
          icon={<Armchair size={18} />}
          hint={total ? `${Math.round((occupied / total) * 100)}%` : "—"}
        />
        <StatCard
          label={t("available_stat")}
          value={String(available)}
          icon={<CheckCircle2 size={18} />}
        />
        <StatCard
          label={t("seats")}
          value={String(totalSeats)}
          icon={<Users size={18} />}
        />
      </div>

      <TablesGrid
        vendorId={vendor.id}
        country={vendor.country}
        slug={vendor.slug}
        theme={vendor.theme}
        tables={tableData}
        t={{
          addTable: t("addTable"),
          tableCount_one: t("tableCount_one"),
          tableCount_other: t("tableCount_other"),
          noTablesYet: t("noTablesYet"),
          qrAutoGenerated: t("qrAutoGenerated"),
          tableCode: t("tableCode"),
          tableCodeHint: t("tableCodeHint"),
          tableCodePlaceholder: t("tableCodePlaceholder"),
          tableCodeRequired: t("tableCodeRequired"),
          tableLabel: t("tableLabel"),
          tableLabelHint: t("tableLabelHint"),
          area: t("area"),
          seats: t("seats"),
          customerUrl: t("customerUrl"),
          copyLink: t("copyLink"),
          copy: t("copy"),
          copied: t("copied"),
          viewMenu: t("viewMenu"),
          toggleStatus: t("toggleStatus"),
          delete: t("delete"),
          deleteConfirmFull: t("deleteConfirmFull"),
          couldNotAddTable: t("couldNotAddTable"),
          createTable: t("createTable"),
          cancel: t("cancel"),
          clickToChangeStatus: t("clickToChangeStatus"),
        }}
      />
    </>
  );
}
